alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: olepunchy.dev
    type: PRIMARY
    zone: olepunchy.dev
name: olepunchy-dev
region: nyc
services:
  - http_port: 80
    image:
      registry: olepunchy
      registry_type: DOCKER_HUB
      repository: olepunchy.dev
      tag: 1.0.7
    instance_count: 1
    instance_size_slug: basic-xxs
    name: olepunchy-dev
    routes:
      - path: /
    source_dir: /
